// GENERATED by scripts/import-ti4-data.mjs — do not edit by hand.
// Source: AsyncTI4/TI4_map_generator_bot (techs + factions)
// Re-run: npm run data:import
import type { Faction } from './faction.types';

export const FACTIONS: readonly Faction[] = [
  { id: 'sardakk', name: 'Sardakk Norr', startingTechIds: [], homePlanetIds: ['quinarra', 'trenlak'], source: 'base', factionTechIds: ['exo2', 'vpw'] },
  { id: 'arborec', name: 'The Arborec', startingTechIds: ['md_c1'], homePlanetIds: ['nestphar'], source: 'base', factionTechIds: ['bio', 'lw2'] },
  { id: 'argent', name: 'The Argent Flight', startingTechIds: [], homePlanetIds: ['valk', 'ylir', 'avar'], source: 'pok', factionTechIds: ['ah', 'swa2'], startingTechChoice: { count: 2, options: ['nm', 'st', 'ps'] } },
  { id: 'letnev', name: 'The Barony of Letnev', startingTechIds: ['amd', 'ps'], homePlanetIds: ['arc_prime', 'wren_terra'], source: 'base', factionTechIds: ['l4', 'nes'] },
  { id: 'saar', name: 'The Clan of Saar', startingTechIds: ['amd'], homePlanetIds: ['ragh', 'lisis_two'], source: 'base', factionTechIds: ['ffac2', 'cm'] },
  { id: 'muaat', name: 'The Embers of Muaat', startingTechIds: ['ps'], homePlanetIds: ['muaat'], source: 'base', factionTechIds: ['pws2', 'mr'] },
  { id: 'hacan', name: 'The Emirates of Hacan', startingTechIds: ['st', 'amd'], homePlanetIds: ['arretze', 'hercant', 'kamdorn'], source: 'base', factionTechIds: ['qdn', 'pm'] },
  { id: 'empyrean', name: 'The Empyrean', startingTechIds: ['det'], homePlanetIds: ['the_dark'], source: 'pok', factionTechIds: ['vw', 'as'] },
  { id: 'sol', name: 'The Federation of Sol', startingTechIds: ['amd', 'nm'], homePlanetIds: ['jord'], source: 'base', factionTechIds: ['so2', 'ac2'] },
  { id: 'ghost', name: 'The Ghosts of Creuss', startingTechIds: ['gd'], homePlanetIds: ['creuss'], source: 'base', factionTechIds: ['ds', 'wg'] },
  { id: 'l1z1x', name: 'The L1Z1X Mindnet', startingTechIds: ['ps', 'nm'], homePlanetIds: ['zero_dot_zero_dot_zero_dot'], source: 'base', factionTechIds: ['is', 'sdn2'] },
  { id: 'mahact', name: 'The Mahact Gene-Sorcerers', startingTechIds: ['pi', 'bs'], homePlanetIds: ['ixth'], source: 'pok', factionTechIds: ['cl2', 'gr'] },
  { id: 'mentak', name: 'The Mentak Coalition', startingTechIds: ['ps', 'st'], homePlanetIds: ['moll_primus'], source: 'base', factionTechIds: ['mc', 'so'] },
  { id: 'naalu', name: 'The Naalu Collective', startingTechIds: ['st', 'nm'], homePlanetIds: ['maaluuk', 'druaa'], source: 'base', factionTechIds: ['ng', 'hcf2'] },
  { id: 'naaz', name: 'The Naaz-Rokha Alliance', startingTechIds: ['pa', 'aida'], homePlanetIds: ['naazir', 'rokha'], source: 'pok', factionTechIds: ['pfa', 'sc'] },
  { id: 'nekro', name: 'The Nekro Virus', startingTechIds: ['dxa'], homePlanetIds: ['mordai_two'], source: 'base', factionTechIds: ['vax', 'vay'] },
  { id: 'nomad', name: 'The Nomad', startingTechIds: ['sr'], homePlanetIds: ['arcturus'], source: 'pok', factionTechIds: ['m2', 'tcs'] },
  { id: 'titans', name: 'The Titans of Ul', startingTechIds: ['amd', 'sdn'], homePlanetIds: ['elysium'], source: 'pok', factionTechIds: ['ht2', 'se2'] },
  { id: 'jolnar', name: 'The Universities of Jol-Nar', startingTechIds: ['amd', 'st', 'nm', 'ps'], homePlanetIds: ['jol', 'nar'], source: 'base', factionTechIds: ['ers', 'scc'] },
  { id: 'cabal', name: 'The Vuil\'raith Cabal', startingTechIds: ['sar'], homePlanetIds: ['acheron'], source: 'pok', factionTechIds: ['dt2', 'vtx'] },
  { id: 'winnu', name: 'The Winnu', startingTechIds: [], homePlanetIds: ['winnu'], source: 'base', factionTechIds: ['lgf', 'htp'], startingTechChoice: { count: 1, options: ['amd', 'det', 'nm', 'pa', 'st', 'sdn', 'aida', 'ps'] } },
  { id: 'xxcha', name: 'The Xxcha Kingdom', startingTechIds: ['gls'], homePlanetIds: ['archon_ren', 'archon_tau'], source: 'base', factionTechIds: ['it', 'nf'] },
  { id: 'yin', name: 'The Yin Brotherhood', startingTechIds: ['st'], homePlanetIds: ['darien'], source: 'base', factionTechIds: ['yso', 'ic'] },
  { id: 'yssaril', name: 'The Yssaril Tribes', startingTechIds: ['nm'], homePlanetIds: ['retillion', 'shalloq'], source: 'base', factionTechIds: ['tp', 'mi'] },
];
